title: Jianglong Zhang's Homepage
page-top-title: Jianglong Zhang
top-section-bg-text: Welcome to my page!
home-subtitle: Jianglong Zhang&ensp;|&ensp;张江龙
copyright-text: '&copy; Jianglong Zhang 2024-2025. All Rights Reserved.'
